{========================================================================================
  Include : DuckDDBAPIs
  Description : Duck DB API'S
  Author : Frédéric Libaud
  **************************************************************************************
  History
  --------------------------------------------------------------------------------------
  2024-06-21 Migration of duckdb.h
========================================================================================}

{$i DuckDBAPIs_Appender.inc}
{$i DuckDBAPIs_Arrow.inc}
{$i DuckDBAPIs_Configuration.inc}
{$i DuckDBAPIs_Data.inc}
{$i DuckDBAPIs_DateTime.inc}
{$i DuckDBAPIs_Decimal.inc}
{$i DuckDBAPIs_Extract.inc}
{$i DuckDBAPIs_Helpers.inc}
{$i DuckDBAPIs_Hugeint.inc}
{$i DuckDBAPIs_Logical.inc}
{$i DuckDBAPIs_Open.inc}
{$i DuckDBAPIs_Pending.inc}
{$i DuckDBAPIs_Prepared.inc}
{$i DuckDBAPIs_Query.inc}
{$i DuckDBAPIs_Replacement.inc}
{$i DuckDBAPIs_Result.inc}
{$i DuckDBAPIs_Streaming.inc}
{$i DuckDBAPIs_Table.inc}
{$i DuckDBAPIs_Threading.inc}
{$i DuckDBAPIs_Value.inc}
{$i DuckDBAPIs_Vector.inc}
{$i DuckDBAPIs_Validity.inc}

