{========================================================================================
  Include : DuckDDBAPIs
  Description : Duck DB API'S
  Author : Frédéric Libaud
  **************************************************************************************
  History
  --------------------------------------------------------------------------------------
  2024-06-21 Migration of duckdb.h
========================================================================================}

{$i DuckDBAPIsAppender.inc}

{$i DuckDBAPIsArrow.inc}

{$i DuckDBAPIsConfiguration.inc}

{$i DuckDBAPIsData.inc}

{$i DuckDBAPIsDateTime.inc}

{$i DuckDBAPIsDecimal.inc}

{$i DuckDBAPIsExtract.inc}

{$i DuckDBAPIsHelpers.inc}

{$i DuckDBAPIsHugeint.inc}

{$i DuckDBAPIsLogical.inc}

{$i DuckDBAPIsOpen.inc}

{$i DuckDBAPIsPending.inc}

{$i DuckDBAPIsPrepared.inc}

{$i DuckDBAPIsQuery.inc}

{$i DuckDBAPIsReplacement.inc}

{$i DuckDBAPIsResult.inc}

{$i DuckDBAPIsStreaming.inc}

{$i DuckDBAPIsTable.inc}

{$i DuckDBAPIsThreading.inc}

{$i DuckDBAPIsValue.inc}

{$i DuckDBAPIsVector.inc}

{$i DuckDBAPIsValidity.inc}

{ end of include file }

